config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'flights#index'
  resources :flights, only: [:index]
  resources :bookings, only: %i[new create show]
end

app/models/airport.rb
class Airport < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  has_many :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers

  belongs_to :flight

  validates :flight_id, presence: true
end

app/models/flight.rb
# frozen_string_literal:true

class Flight < ApplicationRecord
  belongs_to :start_airport, class_name: "Airport", inverse_of: :departing_flights
  belongs_to :end_airport, class_name: "Airport", inverse_of: :arriving_flights
  has_many :bookings, dependent: nil
  has_many :passengers, through: :bookings

  validates :start_airport_id, :end_airport_id, :start_datetime, :flight_duration_minutes, presence: true

  def self.match_search(params, date)
    start_airport_id = params[:start_airport_id].to_i
    end_airport_id = params[:end_airport_id].to_i
    where("start_airport_id = :start_airport_id and
                 end_airport_id = :end_airport_id and start_datetime >= :date",
          { start_airport_id: start_airport_id,
            end_airport_id: end_airport_id,
            date: date })
  end
end

app/models/flight_search.rb
# frozen_string_literal: true

class FlightSearch
  include ActiveModel::Model

  attr_accessor :date, :number_of_passengers, :start_airport_id, :end_airport_id

  validates :number_of_passengers, :start_airport_id, :end_airport_id, :date, presence: true
  validates :date, date: { after_or_equal_to: proc { Date.today } }
end

app/models/passenger.rb
# frozen_string_literal: true

class Passenger < ApplicationRecord
  belongs_to :booking, inverse_of: :passengers
  has_many :flights, through: :bookings

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# frozen_string_literal:true

class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @passengers = @booking.passengers
    params[:number_of_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.create!(booking_params)
    @booking.passengers.each do |passenger|
      PassengerMailer
        .booking_confirmed_email(passenger)
        .deliver_later
    end
    flash[:notice] = 'Flight booked!'
    redirect_to @booking
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  private

  def booking_params
    params
      .require(:booking)
      .permit(:flight_id, passengers_attributes: %i[id name email booking_id])
  end
end

app/controllers/flights_controller.rb
# frozen_string_literal: true

class FlightsController < ApplicationController
  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def index
    if params[:flight_search]
      @flight_search = assign_flight_search(params[:flight_search])
      if @flight_search.valid?
        @flights = Flight.all.match_search(params[:flight_search], @flight_search.date)
        @number_of_passengers = @flight_search.number_of_passengers
        respond_to do |format|
          flash[:notice] = ('No matching flights available' if @flights.blank?)
          format.html { render 'index' }
        end
      else
        respond_to do |format|
          flash.now[:notice] = 'Invalid search criterias'
          format.html { render 'index' }
        end
      end
    end
    @flight_search = FlightSearch.new
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

  private

  def assign_flight_search(params)
    @flight_search ||= FlightSearch.new(flight_search_params)
    @flight_search.date = helpers.convert_dates_to_datetime(params[:date])
    @flight_search.number_of_passengers = params[:number_of_passengers]
    @flight_search
  end

  def flight_search_params
    params.require(:flight_search).permit(:number_of_passengers, :date, :start_airport_id, :end_airport_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal:true

module ApplicationHelper
  def convert_dates_to_datetime(date)
    if date.present?
      Date.parse(date)
    else
      Time.zone.today
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h3>FROM <%= @flight.start_airport.name %> TO <%= @flight.end_airport.name %></h3>
<h4>Flight date: <%= I18n.l(@flight.start_datetime, format: :long) %></h4>
<div class='form-container'>
	<%= form_with model: @booking do |form|%>
		<%= form.label :flight_id, "Flight ID: " %>
		<%= form.number_field :flight_id, value: @flight.id, readonly: true %>
		<%= form.fields_for :passengers  do |passenger_form| %>
			<div class='nested-form-container'>
				<p>Passenger:</p>
				<br>
				<%= passenger_form.label :name, 'Name: ' %>
				<%= passenger_form.text_field :name, :required => true %>
				<br>
				<%= passenger_form.label :email, 'Email: ' %>
				<%= passenger_form.email_field :email, :required => true %>
				<br>
			</div>
		<% end %>
		<br>
		<%= form.submit "Book flight" %>
	<% end %>
</div>

app/views/bookings/show.html.erb
<% if flash[:notice] %>
	<p class='notice'><%= flash[:notice] %></p>
<% end %>
<h2>Booked Flight</h2>
<h3>FROM <%= @flight.start_airport.name %> TO <%= @flight.end_airport.name %></h3>
<h4>Flight date: <%= I18n.l(@flight.start_datetime, format: :long) %></h4>
<div class='list-container'>
	<p>Passengers:</p>
	<ul class= 'passenger-list'>
		<% @passengers.each do |passenger| %>
			<li><%= passenger.name %></li>
		<% end %>
	</ul>
</div>

app/views/flights/_search_form.html.erb
<div class='form-container'>
	<%= form_with model: @flight_search, url: "/", method: :get do |form| %>
		<% if @flight_search.errors.any? %>
			<ul>
				<% @flight_search.errors.full_messages.each do |msg| %>
					<li class='error-msg'><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		<%= form.label :start_airport, "From:" %>
		<%= form.collection_select :start_airport_id, Airport.order(:name), :id, :name %>
		<%= form.label :end_airport, "To:" %>
		<%= form.collection_select :end_airport_id, Airport.order(:name), :id, :name %>
		<%= form.label :number_of_passengers, 'Passengers' %>
		<%= form.number_field :number_of_passengers, in: 1..4, placeholder: 'number of passengers' %>
		<%= form.label :date, 'Date:' %>
		<%= form.date_field :date, start_year: Date.today.year, selected: Date.today, as: :date, class: 'date' %>
		<%= form.submit "Search" %>
	<% end %>
</div>

app/views/flights/_selection_form.html.erb
<div class='form-container'>
	<%= form_with url: new_booking_url, method: :get do |form| %>
		<% @flights.each do |flight| %>
			<%= form.radio_button :flight_id, flight.id  %>
			<%= form.label :flight, "FROM #{flight.start_airport.name} TO #{flight.end_airport.name}" %>
			<ul>
				<li>Flight date: <%= I18n.l(flight.start_datetime, format: :long) %></li>
				<li>Flight duration: <%= distance_of_time_in_words( 0, flight.flight_duration_minutes.minutes ) %></li>
				<li>Number of passengers: <%= @number_of_passengers %></li>
			</ul>
			<%= form.hidden_field :number_of_passengers, value: @number_of_passengers %>
		<% end %>
		<%= form.submit "Book flight" %>
	<% end %>
</div>

app/views/flights/index.html.erb
<%= render 'search_form' %>
<% if @flights.present? %>
	<%= render 'selection_form' %>
<% else %>
	<% if flash[:notice]%>
		<% flash.each do |type, msg| %>
			<div>
				<%= msg %>
			</div>
		<% end %>
	<% end%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <main>
      <h1>Odin Flight Booker</h1>
      <%= yield %>
    </main>
  </body>
</html>